Fixed PydanticUserError due to non-annotated attribute
pydantic.errors.PydanticUserError: A non-annotated attribute was detected: `logging_format_json = '{ "timestamp": "%(asctime)s", "filename": "%(filename)s", "function": "%(funcName)s", "line": "%(lineno)d", "level": "%(levelname)s", "pid": "%(process)d", "thr": "%(thread)d", "message": "%(message)s"}'`. All model fields require a type annotation; if `logging_format_json` is not meant to be a field, you may be able to resolve this error by annotating it as a `ClassVar` or updating `model_config['ignored_types']`.

For further information visit https://errors.pydantic.dev/2.12/u/model-field-missing-annotation